package mvc.View;
/******************
 * Imports
 ******************/
import mvc.Model.CustomerTable;
import mvc.Model.EmployeeTable;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;

public class CE_Frame extends javax.swing.JFrame {
    private String choose;
    private CustomerTable c_model;
    private EmployeeTable e_model;

    
     /**************************
     *  
     *  set look and feel - init GUI and components
     *  
     ***************************/
    
    public CE_Frame(String choose, CustomerTable c_model, EmployeeTable e_model) {
      this.choose = choose;
      this.c_model = c_model;
      this.e_model = e_model;
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CE_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CE_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CE_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CE_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       initComponents();
    }
    
    
       public void init() {
        //set Frame position
        setLocation(
        (Toolkit.getDefaultToolkit().getScreenSize().width-getSize().width) / 2,
        (Toolkit.getDefaultToolkit().getScreenSize().height-getSize().height) / 2
        );
        
        //setup label for customer or employee edit
        if ("Customer".equals(choose)) {
            L_title.setText("Add/Edit Customer");
            L_tele.setVisible(true);
            edt_ctelephone.setVisible(true);
            L_email.setText("Email");
            chb_new.setText("new Customer ?");
        } else { 
            L_title.setText("Add/Edit Employee");
            L_tele.setVisible(false);
            edt_ctelephone.setVisible(false);
            L_email.setText("Troubleshooter");
            chb_new.setText("new Employee ?");
        }
        this.setVisible(true);
       }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_icon = new javax.swing.JLabel();
        L_title = new javax.swing.JLabel();
        L_firstname = new javax.swing.JLabel();
        L_lastname = new javax.swing.JLabel();
        L_email = new javax.swing.JLabel();
        L_tele = new javax.swing.JLabel();
        L_username = new javax.swing.JLabel();
        L_id = new javax.swing.JLabel();
        L_password = new javax.swing.JLabel();
        edt_cfirstname = new javax.swing.JTextField();
        edt_clastname = new javax.swing.JTextField();
        edt_cusername = new javax.swing.JTextField();
        edt_ctelephone = new javax.swing.JTextField();
        edt_cemail = new javax.swing.JTextField();
        edt_cpassword = new javax.swing.JTextField();
        edt_ID = new javax.swing.JTextField();
        btn_csave = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_csearch = new javax.swing.JButton();
        chb_new = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        L_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/View/pics/Customer.png"))); // NOI18N

        L_title.setFont(new java.awt.Font("Tahoma", 1, 18));
        L_title.setText("Add/Edit Customer");

        L_firstname.setText("Firstname");

        L_lastname.setText("Lastname");

        L_email.setText("Email");

        L_tele.setText("Telephone");

        L_username.setText("Username");

        L_id.setText("ID");

        L_password.setText("Password");

        edt_ctelephone.setMinimumSize(new java.awt.Dimension(6, 60));

        edt_cemail.setMinimumSize(new java.awt.Dimension(200, 60));

        edt_cpassword.setMinimumSize(new java.awt.Dimension(6, 60));

        btn_csave.setText("Save");

        btn_cancel.setText("Cancel");

        btn_csearch.setText("Search");

        chb_new.setText("new Customer? ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(L_icon)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_username)
                            .addComponent(L_id)
                            .addComponent(L_firstname)
                            .addComponent(L_lastname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edt_cfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(edt_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(edt_clastname)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(edt_cusername)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_tele)
                                    .addComponent(L_email)
                                    .addComponent(L_password))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_csave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(edt_cpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(edt_cemail, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(edt_ctelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_csearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addComponent(chb_new, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(L_title))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_id)
                            .addComponent(btn_csearch)
                            .addComponent(chb_new))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edt_cfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_firstname)
                            .addComponent(L_tele)
                            .addComponent(edt_ctelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edt_clastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_lastname)
                            .addComponent(L_email, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edt_cemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edt_cusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_password)
                            .addComponent(edt_cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(L_username))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_csave)
                    .addComponent(btn_cancel))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(L_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**************************
     *  ActionEvents
     *  Buttons
     *  Textfield
     ***************************/
    
    /**************
     *  Buttons
     ***************/
    public void setbtn_cancelListener(ActionListener l){
        btn_cancel.addActionListener(l);
    }
    
    public void setbtn_csearchListener(ActionListener l){
        btn_csearch.addActionListener(l);
    }
    
    public void setbtn_saveListener(ActionListener l){
        btn_csave.addActionListener(l);
    }
    
    public void setchb_newListener(ItemListener l){
        chb_new.addItemListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_email;
    private javax.swing.JLabel L_firstname;
    private javax.swing.JLabel L_icon;
    private javax.swing.JLabel L_id;
    private javax.swing.JLabel L_lastname;
    private javax.swing.JLabel L_password;
    private javax.swing.JLabel L_tele;
    private javax.swing.JLabel L_title;
    private javax.swing.JLabel L_username;
    public javax.swing.JButton btn_cancel;
    public javax.swing.JButton btn_csave;
    public javax.swing.JButton btn_csearch;
    public javax.swing.JCheckBox chb_new;
    public javax.swing.JTextField edt_ID;
    public javax.swing.JTextField edt_cemail;
    public javax.swing.JTextField edt_cfirstname;
    public javax.swing.JTextField edt_clastname;
    public javax.swing.JTextField edt_cpassword;
    public javax.swing.JTextField edt_ctelephone;
    public javax.swing.JTextField edt_cusername;
    // End of variables declaration//GEN-END:variables
}
