package Helpdesk.java.helpdesk.mvc.View;
/******************
 * Imports
 ******************/
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.awt.event.ItemListener;

public class Ticket_Frame extends javax.swing.JFrame {
    
    
     /**************************
     *  set look and feel - 
     * init GUI and components
     *  
     ***************************/
    public Ticket_Frame() {
              /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        initComponents();
    }
    
    public void init(){ 
        setLocation(
            (Toolkit.getDefaultToolkit().getScreenSize().width-getSize().width) / 2,
            (Toolkit.getDefaultToolkit().getScreenSize().height-getSize().height) / 2
        );
        this.setVisible(true);
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        edt_ID = new javax.swing.JTextField();
        edt_created = new javax.swing.JTextField();
        edt_update = new javax.swing.JTextField();
        edt_problem = new javax.swing.JTextField();
        scrollpane_solution = new javax.swing.JScrollPane();
        edt_solution = new javax.swing.JTextArea();
        btn_save = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        cmb_category = new javax.swing.JComboBox();
        cmb_status = new javax.swing.JComboBox();
        edt_note = new javax.swing.JTextField();
        cmb_eID = new javax.swing.JComboBox();
        cmb_cID = new javax.swing.JComboBox();
        chb_new = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        edt_topic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ls_products = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(690, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Add/Edit Ticket");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 160, -1));

        jLabel2.setText("Ticket ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 50, -1));

        jLabel3.setText("Problem Category");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setText("Ticket Status");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, -1));

        jLabel5.setText("Employee ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel8.setText("Customer ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 80, -1));

        jLabel10.setText(" Note");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, -1));

        jLabel11.setText("Topic");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 70, -1));

        jLabel12.setText("Solution");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 60, -1));

        jLabel13.setText("Created on");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 70, 17));

        jLabel14.setText("Last Update");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 80, -1));
        getContentPane().add(edt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 183, -1));

        edt_created.setEditable(false);
        getContentPane().add(edt_created, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 220, -1));

        edt_update.setEditable(false);
        getContentPane().add(edt_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 220, -1));
        getContentPane().add(edt_problem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 182, -1));

        edt_solution.setColumns(20);
        edt_solution.setLineWrap(true);
        edt_solution.setRows(5);
        scrollpane_solution.setViewportView(edt_solution);

        getContentPane().add(scrollpane_solution, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 530, 340));

        btn_save.setText("Save");
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 680, 100, -1));

        btn_cancel.setText("Cancel");
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 680, 100, -1));
        getContentPane().add(cmb_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 180, -1));
        getContentPane().add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, -1));
        getContentPane().add(edt_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 182, -1));
        getContentPane().add(cmb_eID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 180, -1));
        getContentPane().add(cmb_cID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 220, -1));

        chb_new.setText("new Ticket?");
        getContentPane().add(chb_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 110, -1));

        jLabel6.setText("Problem");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, -1));
        getContentPane().add(edt_topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 182, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Helpdesk/java/helpdesk/mvc/View/pics/my-tickets.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 210));

        jLabel9.setText("Product");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 70, -1));

        jScrollPane1.setViewportView(ls_products);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 220, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**************************
     *  ActionEvents
     *  Buttons
     *  Textfield
     ***************************/
    
    /**************
     *  Buttons
     ***************/
    
    public void setbtn_cancelListener(ActionListener l){
        btn_cancel.addActionListener(l);
    }
    
    public void setbtn_saveListener(ActionListener l){
        btn_save.addActionListener(l);
    }
    
    public void setchb_newListener(ItemListener l){
        chb_new.addItemListener(l);
    }
    
    public void setFocusListener(FocusListener l){
        edt_ID.addFocusListener(l);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cancel;
    public javax.swing.JButton btn_save;
    public javax.swing.JCheckBox chb_new;
    public javax.swing.JComboBox cmb_cID;
    public javax.swing.JComboBox cmb_category;
    public javax.swing.JComboBox cmb_eID;
    public javax.swing.JComboBox cmb_status;
    public javax.swing.JTextField edt_ID;
    public javax.swing.JTextField edt_created;
    public javax.swing.JTextField edt_note;
    public javax.swing.JTextField edt_problem;
    public javax.swing.JTextArea edt_solution;
    public javax.swing.JTextField edt_topic;
    public javax.swing.JTextField edt_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList ls_products;
    private javax.swing.JScrollPane scrollpane_solution;
    // End of variables declaration//GEN-END:variables

}
